language: php

cache:
    directories:
    - $HOME/.composer/cache

php:
    - '7.1'
    - '7.2'
    - '7.3'
    - '7.4'
    - nightly

env:
    - COMPOSER_FLAGS="--prefer-lowest --prefer-stable"
    - COMPOSER_FLAGS="--prefer-stable"

matrix:
    fast_finish: true
    allow_failures:
        - php: nightly

install:
    - composer update $COMPOSER_FLAGS --no-interaction --prefer-dist --no-progress --no-suggest --ansi

script:
    - vendor/bin/phpunit

